name: CI - MLflow Project Re-training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # <- penting untuk bisa push ke repo

jobs:
  mlflow_retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MLProject/conda.yaml || true
        pip install -r MLProject/requirements.txt || true
        pip install mlflow scikit-learn matplotlib seaborn pandas joblib

    - name: Set MLflow Tracking URI
      run: echo "MLFLOW_TRACKING_URI=file://$(pwd)/MLProject/mlruns" >> $GITHUB_ENV

    - name: Run MLflow training script
      run: |
        cd MLProject
        Python modelling.py

    - name: Upload model-artifacts to GitHub
      if: success()
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git pull origin main  # Untuk menghindari konflik push
        cd MLProject

        if [ -d "mlruns" ] && [ "$(ls -A mlruns)" ]; then
          git add mlruns
        fi

        if $changes; then
          git commit -m "Add model artifacts and mlruns from CI run"
          git push origin main
        else
          echo "No new artifacts to commit."
        fi

    - name: Post Set up Python 3.12.7
      run: echo "Python setup done."

    - name: Post Run actions/checkout@v3
      run: echo "Checkout complete."
